#!/usr/bin/env python3
"""
Evaluate candidate training sessions for the PILOT007 XGBoost motor imagery
decoder using covariance-space discriminability + per-session LOO contribution.

Methodology is documented in SoftwareDocs/projects/harmony-bci/datasets/selection-report.md
(generated by this script).

Stages (independently runnable via --stage):
  cache     -- load XDFs, segment, whiten covariances (mu + beta), save pickle
  fisher    -- Riemannian Fisher score per session in mu and beta bands
  direction -- per-session MI/REST discriminant direction + pairwise alignment
               (diagnoses "anti-aligned" sessions whose MI direction is the
               pool's REST direction — this is what Fisher magnitude misses)
  loo       -- session-LOO baseline + per-session ablation contributions using
               concatenated mu+beta tangent features, matching production XGB
  report    -- write the Markdown report from cache contents
  all       -- cache + fisher + direction + loo + report

Reuses the canonical xgb_cov pipeline without duplicating preprocessing:
  - Utils.stream_utils.load_xdf
  - Utils.xgb_feature_pipeline.segment_and_extract_cov_erd
  - Generate_Riemannian_adaptive.compute_processed_covariances(model_type='xgb')
"""

import argparse
import os
import pickle
import re
import sys
import time
from collections import Counter

os.environ.setdefault("NUMBA_DISABLE_CACHING", "1")
os.environ.setdefault("MNE_USE_NUMBA", "false")

import numpy as np

import config
import Generate_Riemannian_adaptive as base
from Utils.stream_utils import load_xdf
from Utils.xgb_feature_pipeline import segment_and_extract_cov_erd

from pyriemann.tangentspace import TangentSpace, tangent_space
from pyriemann.utils.mean import mean_riemann
from pyriemann.utils.distance import distance_riemann

from sklearn.model_selection import GroupKFold
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    roc_auc_score,
    log_loss,
    balanced_accuracy_score,
)


DEFAULT_CACHE_PATH = "/home/arman-admin/Documents/SoftwareDocs/projects/harmony-bci/datasets/data/selection-cache.pkl"
DEFAULT_REPORT_PATH = "/home/arman-admin/Documents/SoftwareDocs/projects/harmony-bci/datasets/selection-report.md"

TRAINING_DATA_ROOT = os.path.join(
    config.DATA_DIR, f"sub-{config.TRAINING_SUBJECT}", "training_data"
)

# (label, relative subdirectory). Order controls which category a file's
# visual_category ends up as when the same filename appears in more than one.
CATEGORY_DIRS = [
    ("OG_Right",       "OG_Right"),
    ("Contralateral",  "TEMP_RIGHT/Contralateral"),
    ("Ipsilateral",    "TEMP_RIGHT/Ipsilateral"),
    ("Bilateral",      "TEMP_RIGHT/Bilateral"),
]

FILENAME_RE = re.compile(r"sub-(.+?)_ses-(.+?)_task-")

MI_LABEL = 200
REST_LABEL = 100


# ---------------- shared helpers ----------------

def _parse_subject_session(fname: str) -> tuple[str, str]:
    m = FILENAME_RE.search(fname)
    if not m:
        raise ValueError(f"cannot parse subject/session from filename: {fname}")
    return m.group(1), m.group(2)


def _collect_candidates() -> list[dict]:
    """Walk the four category directories, dedupe by filename, preserve category aliases."""
    seen: dict[str, dict] = {}
    for category, rel in CATEGORY_DIRS:
        full = os.path.join(TRAINING_DATA_ROOT, rel)
        if not os.path.isdir(full):
            print(f"  [warn] missing category dir: {full}", file=sys.stderr)
            continue
        for fname in sorted(os.listdir(full)):
            if not fname.endswith(".xdf") or "OBS" in fname:
                continue
            fpath = os.path.join(full, fname)
            if fname in seen:
                seen[fname]["aliased_categories"].append(category)
                continue
            subj, sess = _parse_subject_session(fname)
            seen[fname] = {
                "file_path": fpath,
                "subject_id": subj,
                "session_tag": sess,
                "visual_category": category,
                "aliased_categories": [],
            }
    return sorted(seen.values(), key=lambda s: (s["subject_id"], s["session_tag"]))


def _fit_tangent_ref(covs: np.ndarray) -> np.ndarray:
    ts = TangentSpace(metric="riemann")
    ts.fit(covs)
    return ts.reference_


def _project(covs: np.ndarray, ref: np.ndarray) -> np.ndarray:
    return tangent_space(covs, ref, metric="riemann")


def _get_xgb_params() -> dict:
    """Mirror train_xgb_dual_thresholds parameter construction, without plotting."""
    p = dict(
        n_estimators=int(getattr(config, "XGB_N_ESTIMATORS", 300)),
        max_depth=int(getattr(config, "XGB_MAX_DEPTH", 6)),
        objective="binary:logistic",
        eval_metric="logloss",
        random_state=42,
        verbosity=0,
    )
    for pname, ckey, cast in [
        ("learning_rate",    "XGB_LEARNING_RATE",    float),
        ("subsample",        "XGB_SUBSAMPLE",        float),
        ("colsample_bytree", "XGB_COLSAMPLE_BYTREE", float),
        ("reg_alpha",        "XGB_REG_ALPHA",        float),
        ("reg_lambda",       "XGB_REG_LAMBDA",       float),
        ("min_child_weight", "XGB_MIN_CHILD_WEIGHT", float),
    ]:
        v = getattr(config, ckey, None)
        if v is not None:
            p[pname] = cast(v)
    return p


def _load_cache(cache_path: str) -> dict:
    with open(cache_path, "rb") as f:
        return pickle.load(f)


def _save_cache(cache_path: str, cache: dict) -> None:
    os.makedirs(os.path.dirname(cache_path), exist_ok=True)
    with open(cache_path, "wb") as f:
        pickle.dump(cache, f)


# ---------------- stage: cache ----------------

def stage_cache(cache_path: str) -> None:
    import mne
    mne.set_log_level("WARNING")

    candidates = _collect_candidates()
    print(f"[cache] {len(candidates)} unique candidate files under {TRAINING_DATA_ROOT}")

    sessions: list[dict] = []
    for i, meta in enumerate(candidates, 1):
        t0 = time.time()
        print(f"[cache] ({i}/{len(candidates)}) {os.path.basename(meta['file_path'])}  "
              f"[{meta['visual_category']}]")
        eeg_stream, marker_stream = load_xdf(meta["file_path"], report=False)
        segments_mu, labels, _erd, segments_beta, _ch = segment_and_extract_cov_erd(
            eeg_stream,
            marker_stream,
            compute_erd=False,
            apply_csd=False,
            return_beta_segments=True,
        )
        cov_mu = base.compute_processed_covariances(
            segments_mu, labels, model_type="xgb"
        )
        cov_beta = base.compute_processed_covariances(
            segments_beta, labels, model_type="xgb"
        )
        n_mi = int((labels == MI_LABEL).sum())
        n_rest = int((labels == REST_LABEL).sum())
        sessions.append({
            **meta,
            "covariances_mu":   np.asarray(cov_mu,   dtype=np.float64),
            "covariances_beta": np.asarray(cov_beta, dtype=np.float64),
            "labels":           np.asarray(labels, dtype=np.int32),
            "n_mi":             n_mi,
            "n_rest":           n_rest,
        })
        print(f"    -> n_windows={len(labels)} (MI={n_mi}, REST={n_rest})  "
              f"cov_mu={cov_mu.shape[1:]} cov_beta={cov_beta.shape[1:]}  "
              f"[{time.time()-t0:.1f}s]")

    cache = {
        "schema_version": 2,
        "config_snapshot": {
            "SHRINKAGE_PARAM_XGB": float(config.SHRINKAGE_PARAM_XGB),
            "LOWCUT":               float(config.LOWCUT),
            "HIGHCUT":              float(config.HIGHCUT),
            "SELECT_MOTOR_CHANNELS": int(config.SELECT_MOTOR_CHANNELS),
            "MOTOR_CHANNEL_NAMES":   list(config.MOTOR_CHANNEL_NAMES),
            "CLASSIFY_WINDOW":       int(config.CLASSIFY_WINDOW),
            "RECENTERING":           int(config.RECENTERING),
            "XGB_MAX_DEPTH":     int(getattr(config, "XGB_MAX_DEPTH", 6)),
            "XGB_N_ESTIMATORS":  int(getattr(config, "XGB_N_ESTIMATORS", 300)),
            "XGB_LEARNING_RATE": float(getattr(config, "XGB_LEARNING_RATE", 0.1)),
        },
        "sessions": sessions,
        "fisher":   None,
        "loo":      None,
    }
    _save_cache(cache_path, cache)
    print(f"[cache] wrote {cache_path}")


# ---------------- stage: fisher ----------------

def _riemannian_fisher(covs: np.ndarray, labels: np.ndarray) -> float:
    """
    Squared Riemannian Fisher score:
        d_R(μ_MI, μ_REST)^2 / mean( ⟨d_R(·, μ_MI)^2⟩, ⟨d_R(·, μ_REST)^2⟩ ).

    Numerator and denominator are both squared Riemannian distances so the ratio
    is scale-consistent; this is the direct analogue of the classical
    Fisher criterion (between-class variance / within-class variance) under
    the affine-invariant Riemannian metric used throughout the decoder.
    """
    mi   = covs[labels == MI_LABEL]
    rest = covs[labels == REST_LABEL]
    if len(mi) < 2 or len(rest) < 2:
        return float("nan")
    mu_mi   = mean_riemann(mi)
    mu_rest = mean_riemann(rest)
    d_between_sq = float(distance_riemann(mu_mi, mu_rest)) ** 2
    var_mi   = float(np.mean([distance_riemann(c, mu_mi)   ** 2 for c in mi]))
    var_rest = float(np.mean([distance_riemann(c, mu_rest) ** 2 for c in rest]))
    sigma_within_sq = 0.5 * (var_mi + var_rest)
    if sigma_within_sq <= 0.0:
        return float("inf")
    return d_between_sq / sigma_within_sq


def _require_schema_v2(cache: dict) -> None:
    if int(cache.get("schema_version", 1)) < 2:
        raise RuntimeError(
            "cache is schema v1 (mu-only). Re-run `--stage cache` to add beta-band "
            "covariances required by the updated fisher/direction/loo stages."
        )


def stage_fisher(cache_path: str) -> None:
    cache = _load_cache(cache_path)
    _require_schema_v2(cache)
    print(f"[fisher] scoring {len(cache['sessions'])} sessions in mu and beta bands")

    max_scores: list[float] = []
    for s in cache["sessions"]:
        fm = _riemannian_fisher(s["covariances_mu"],   s["labels"])
        fb = _riemannian_fisher(s["covariances_beta"], s["labels"])
        fx = float(np.nanmax([fm, fb]))
        s["fisher_score_mu"]   = fm
        s["fisher_score_beta"] = fb
        s["fisher_score_max"]  = fx
        max_scores.append(fx)
        print(f"    Fisher mu={fm:6.3f} beta={fb:6.3f} max={fx:6.3f}  "
              f"{s['subject_id']:<20} {s['session_tag']:<22} ({s['visual_category']})")

    valid = np.array([x for x in max_scores if np.isfinite(x)])
    if len(valid) == 0:
        raise RuntimeError("no finite Fisher scores -- check cache")
    thresh = float(valid.mean() - valid.std())

    for s in cache["sessions"]:
        s["fisher_screened_in"] = bool(
            np.isfinite(s["fisher_score_max"]) and s["fisher_score_max"] >= thresh
        )

    cache["fisher"] = {
        "threshold":      thresh,
        "mean":           float(valid.mean()),
        "std":            float(valid.std()),
        "combiner":       "max(fisher_mu, fisher_beta)",
        "threshold_rule": "mean - std of max-fisher across sessions",
    }

    kept    = [s for s in cache["sessions"] if s["fisher_screened_in"]]
    dropped = [s for s in cache["sessions"] if not s["fisher_screened_in"]]
    print(f"[fisher] mean(max)={valid.mean():.3f}  std={valid.std():.3f}  "
          f"threshold = {thresh:.3f}  (combiner = max over bands)")
    print(f"[fisher] kept {len(kept)} / dropped {len(dropped)}")
    for s in dropped:
        print(f"    DROP  max_fisher={s['fisher_score_max']:.3f}  "
              f"(mu={s['fisher_score_mu']:.3f} beta={s['fisher_score_beta']:.3f})  "
              f"{s['subject_id']} {s['session_tag']}")

    _save_cache(cache_path, cache)


# ---------------- stage: direction ----------------

def _session_discriminant(
    cov_mu: np.ndarray,
    cov_beta: np.ndarray,
    labels: np.ndarray,
) -> np.ndarray:
    """
    Per-session MI vs REST discriminant direction in tangent space at identity,
    concatenated over mu and beta bands.

    Identity is the natural base point because the per-session Riemannian
    whitener centers each session's covariances on the identity — so class
    means live in a tangent space around identity that is directly comparable
    across sessions.

    Returns a 1-D vector of length 2 * n_ch * (n_ch + 1) / 2.
    """
    mi   = labels == MI_LABEL
    rest = labels == REST_LABEL
    parts = []
    for covs in (cov_mu, cov_beta):
        if mi.sum() < 2 or rest.sum() < 2:
            return np.full(2 * covs.shape[-1] * (covs.shape[-1] + 1) // 2, np.nan)
        mu_mi   = mean_riemann(covs[mi])
        mu_rest = mean_riemann(covs[rest])
        ref = np.eye(covs.shape[-1])
        proj = tangent_space(np.stack([mu_mi, mu_rest]), ref, metric="riemann")
        parts.append(proj[0] - proj[1])
    return np.concatenate(parts)


def stage_direction(cache_path: str) -> None:
    """
    Compute per-session discriminant direction vectors and their pairwise
    cosine similarity. The alignment score of session s is the mean cosine
    similarity between s's discriminant and every other session's.

    Interpretation:
      ≈ +0.3 to 1.0  majority-aligned (typical MI direction)
      ≈  0          orthogonal / novel mode (keep — this is "different MI")
      < -0.2        anti-aligned (this session's MI direction is the pool's
                    REST direction — the session effectively contradicts the
                    others; investigate or drop)
    """
    cache = _load_cache(cache_path)
    _require_schema_v2(cache)
    n = len(cache["sessions"])
    print(f"[direction] computing discriminants for {n} sessions")

    V = []
    for s in cache["sessions"]:
        v = _session_discriminant(s["covariances_mu"], s["covariances_beta"], s["labels"])
        V.append(v)
    V = np.asarray(V, dtype=np.float64)

    finite_rows = np.all(np.isfinite(V), axis=1)
    if finite_rows.sum() < 2:
        raise RuntimeError("need >= 2 sessions with finite discriminants for alignment")

    norms = np.linalg.norm(V, axis=1, keepdims=True) + 1e-12
    Vn = V / norms
    cos_mat = Vn @ Vn.T
    np.fill_diagonal(cos_mat, np.nan)

    for i, s in enumerate(cache["sessions"]):
        row = cos_mat[i][np.isfinite(cos_mat[i])]
        s["alignment_score"] = float(np.mean(row)) if row.size else float("nan")
        print(f"    alignment={s['alignment_score']:+.3f}  "
              f"{s['subject_id']:<20} {s['session_tag']:<22} ({s['visual_category']})")

    cache["direction"] = {
        "session_order":    [s["file_path"] for s in cache["sessions"]],
        "cosine_matrix":    cos_mat.tolist(),
        "base_point":       "identity (per-session whitening centers covs at I)",
        "bands_included":   ["mu", "beta"],
    }
    _save_cache(cache_path, cache)


# ---------------- CV helper used by loo ----------------

METRIC_NAMES = ("acc", "auc", "log_loss", "balanced_acc")


def _summarize_folds(per_fold: list[dict]) -> dict:
    """Mean/std/min/max across folds for each metric (ignoring NaN folds)."""
    summary = {}
    for m in METRIC_NAMES:
        vals = np.array([f[m] for f in per_fold], dtype=float)
        finite = vals[np.isfinite(vals)]
        summary[m] = {
            "mean":     float(finite.mean()) if len(finite) else float("nan"),
            "std":      float(finite.std())  if len(finite) else float("nan"),
            "min":      float(finite.min())  if len(finite) else float("nan"),
            "max":      float(finite.max())  if len(finite) else float("nan"),
            "n_finite": int(len(finite)),
        }
    return summary


def _loo_cv(
    sessions_subset: list[dict],
    xgb_params: dict,
    shuffle_labels: bool = False,
    shuffle_seed: int = 0,
) -> dict:
    """
    Session-LOO CV across `sessions_subset`. One fold per session.
    For each fold: fit tangent references on train covariances (leakage-free)
    for both mu and beta bands, project train/test, concatenate features,
    StandardScaler, XGBoost. Report argmax accuracy, AUC, log-loss, and
    balanced accuracy. Feature stacking matches production XGB (XGB_USE_COV_BETA=1).

    If `shuffle_labels` is True, labels are permuted *within each session*
    (preserving per-session class balance) before CV. This gives a null
    baseline that anchors what "chance" looks like on this pool.

    Returns:
        {
          "per_fold": [
            {"file_path": ..., "n_trials": int,
             "acc": float, "auc": float, "log_loss": float, "balanced_acc": float},
            ...
          ],
          "summary": {metric: {"mean", "std", "min", "max", "n_finite"}},
        }
    """
    from xgboost import XGBClassifier

    n_sessions = len(sessions_subset)
    if n_sessions < 2:
        raise ValueError("need >= 2 sessions for session-LOO")

    cov_mu_all   = np.concatenate([s["covariances_mu"]   for s in sessions_subset], axis=0)
    cov_beta_all = np.concatenate([s["covariances_beta"] for s in sessions_subset], axis=0)
    all_labels   = np.concatenate([s["labels"]           for s in sessions_subset])
    file_paths   = [s["file_path"] for s in sessions_subset]
    group_ids    = np.concatenate([
        np.full(len(s["labels"]), i, dtype=int) for i, s in enumerate(sessions_subset)
    ])

    classes = np.sort(np.unique(all_labels))
    if len(classes) != 2:
        raise ValueError(f"expected binary labels, got {classes}")
    mi_label = int(classes[1])
    y_bin = (all_labels == mi_label).astype(int)

    if shuffle_labels:
        rng = np.random.default_rng(shuffle_seed)
        y_shuf = y_bin.copy()
        for g in np.unique(group_ids):
            idx = np.where(group_ids == g)[0]
            y_shuf[idx] = rng.permutation(y_shuf[idx])
        y_bin = y_shuf

    gkf = GroupKFold(n_splits=n_sessions)
    per_fold: list[dict] = []

    for tr, te in gkf.split(cov_mu_all, groups=group_ids):
        held = int(group_ids[te[0]])
        ref_mu   = _fit_tangent_ref(cov_mu_all[tr])
        ref_beta = _fit_tangent_ref(cov_beta_all[tr])
        X_tr = np.hstack([
            _project(cov_mu_all[tr],   ref_mu),
            _project(cov_beta_all[tr], ref_beta),
        ])
        X_te = np.hstack([
            _project(cov_mu_all[te],   ref_mu),
            _project(cov_beta_all[te], ref_beta),
        ])
        scaler = StandardScaler()
        Xs_tr = scaler.fit_transform(X_tr)
        Xs_te = scaler.transform(X_te)
        clf = XGBClassifier(**xgb_params)
        clf.fit(Xs_tr, y_bin[tr])

        y_true  = y_bin[te]
        y_pred  = clf.predict(Xs_te)
        y_proba = clf.predict_proba(Xs_te)[:, 1]

        acc = float((y_pred == y_true).mean())
        # AUC undefined when held-out fold is single-class.
        auc = (float(roc_auc_score(y_true, y_proba))
               if len(np.unique(y_true)) == 2 else float("nan"))
        ll  = float(log_loss(y_true, y_proba, labels=[0, 1]))
        bal = float(balanced_accuracy_score(y_true, y_pred))

        per_fold.append({
            "file_path":    file_paths[held],
            "n_trials":     int(len(y_true)),
            "acc":          acc,
            "auc":          auc,
            "log_loss":     ll,
            "balanced_acc": bal,
        })

    return {"per_fold": per_fold, "summary": _summarize_folds(per_fold)}


# ---------------- stage: loo ----------------

def stage_loo(cache_path: str) -> None:
    cache = _load_cache(cache_path)
    _require_schema_v2(cache)
    if cache.get("fisher") is None:
        raise RuntimeError("run --stage fisher first")

    screened = [s for s in cache["sessions"] if s.get("fisher_screened_in")]
    if len(screened) < 2:
        raise RuntimeError("need >= 2 Fisher-screened sessions for LOO")

    print(f"[loo] running on {len(screened)} Fisher-screened sessions")
    xgb_params = _get_xgb_params()
    t_start = time.time()

    # --- Baseline: full screened pool ---
    t0 = time.time()
    baseline = _loo_cv(screened, xgb_params)
    bs = baseline["summary"]
    print(f"[loo] baseline  "
          f"acc={bs['acc']['mean']:.4f}±{bs['acc']['std']:.4f}  "
          f"AUC={bs['auc']['mean']:.4f}±{bs['auc']['std']:.4f}  "
          f"logloss={bs['log_loss']['mean']:.4f}  "
          f"balAcc={bs['balanced_acc']['mean']:.4f}  "
          f"[{time.time()-t0:.1f}s]")

    # --- Null: labels shuffled within session (preserves class balance) ---
    t0 = time.time()
    null_baseline = _loo_cv(screened, xgb_params, shuffle_labels=True, shuffle_seed=0)
    ns = null_baseline["summary"]
    print(f"[loo] null      "
          f"acc={ns['acc']['mean']:.4f}  "
          f"AUC={ns['auc']['mean']:.4f}  "
          f"logloss={ns['log_loss']['mean']:.4f}  "
          f"balAcc={ns['balanced_acc']['mean']:.4f}  "
          f"[{time.time()-t0:.1f}s]")

    # --- Ablations: full per-fold results stored so report can derive
    #     scalar contributions and the per-session-pair impact matrix. ---
    ablations: dict[str, dict] = {}
    for i, hold in enumerate(screened, 1):
        t1 = time.time()
        subset = [s for s in screened if s["file_path"] != hold["file_path"]]
        ab = _loo_cv(subset, xgb_params)
        ablations[hold["file_path"]] = ab
        absum = ab["summary"]
        contrib_acc = bs["acc"]["mean"] - absum["acc"]["mean"]
        contrib_auc = bs["auc"]["mean"] - absum["auc"]["mean"]
        elapsed_total = time.time() - t_start
        eta_sec = (elapsed_total / (i + 1)) * (len(screened) - i) if i < len(screened) else 0.0
        print(f"[loo] ({i}/{len(screened)}) drop {hold['subject_id']} {hold['session_tag']}: "
              f"contrib_acc={contrib_acc:+.4f}  contrib_auc={contrib_auc:+.4f}  "
              f"[{time.time()-t1:.1f}s, eta {eta_sec/60:.1f}m]")

    cache["schema_version"] = 3
    cache["loo"] = {
        "metric_names":  list(METRIC_NAMES),
        "baseline":      baseline,
        "null_baseline": null_baseline,
        "ablations":     ablations,
    }
    _save_cache(cache_path, cache)
    print(f"[loo] total elapsed {(time.time()-t_start)/3600:.2f}h")


# ---------------- stage: report ----------------

# For log_loss, smaller is better, so flip the sign of all derived quantities
# (contributions, impacts) so "positive = good for the pool" holds uniformly.
_METRIC_SIGN = {"acc": +1.0, "auc": +1.0, "log_loss": -1.0, "balanced_acc": +1.0}
_METRIC_LABEL = {
    "acc":          "Acc",
    "auc":          "AUC",
    "log_loss":     "LogLoss",
    "balanced_acc": "BalAcc",
}


def _fmt(x, spec=".4f"):
    return format(x, spec) if x is not None and np.isfinite(x) else "—"


def _compute_contributions(baseline_summary: dict, ablations: dict) -> dict:
    """
    contributions[fp][metric] = signed improvement from including session fp.
    Positive always means "including this session helps the pool" (log_loss flipped).
    """
    out: dict[str, dict[str, float]] = {}
    for fp, ab in ablations.items():
        out[fp] = {}
        for m in METRIC_NAMES:
            b = baseline_summary[m]["mean"]
            a = ab["summary"][m]["mean"]
            if np.isfinite(b) and np.isfinite(a):
                out[fp][m] = _METRIC_SIGN[m] * (b - a)
            else:
                out[fp][m] = float("nan")
    return out


def _compute_impact_matrix(baseline_per_fold: list[dict], ablations: dict) -> dict:
    """
    impact[i_fp][j_fp][metric] = how much including session i improves the
    pool's prediction of session j (when j is held out). Positive = i helps j;
    negative = i hurts j. Undefined for i == j. log_loss is sign-flipped so
    positive uniformly means "good".
    """
    baseline_by_fp = {f["file_path"]: f for f in baseline_per_fold}
    impact: dict[str, dict[str, dict[str, float]]] = {}
    for i_fp, ab in ablations.items():
        impact[i_fp] = {}
        ab_by_fp = {f["file_path"]: f for f in ab["per_fold"]}
        for j_fp, ab_fold in ab_by_fp.items():
            bl_fold = baseline_by_fp.get(j_fp)
            if bl_fold is None:
                continue
            impact[i_fp][j_fp] = {}
            for m in METRIC_NAMES:
                b = bl_fold[m]
                a = ab_fold[m]
                if np.isfinite(b) and np.isfinite(a):
                    impact[i_fp][j_fp][m] = _METRIC_SIGN[m] * (b - a)
                else:
                    impact[i_fp][j_fp][m] = float("nan")
    return impact


def stage_report(cache_path: str, report_path: str) -> None:
    cache = _load_cache(cache_path)
    sessions = cache["sessions"]

    subj_counts = Counter(s["subject_id"] for s in sessions)
    unique_subjs = {s for s, c in subj_counts.items() if c == 1}

    fisher_info  = cache.get("fisher")    or {}
    direction    = cache.get("direction") or {}
    loo          = cache.get("loo")       or {}
    loo_is_new = isinstance(loo.get("baseline"), dict)

    baseline      = loo.get("baseline")      if loo_is_new else None
    null_baseline = loo.get("null_baseline") if loo_is_new else None
    ablations     = loo.get("ablations", {}) if loo_is_new else {}

    baseline_per_fold_by_fp = (
        {f["file_path"]: f for f in baseline["per_fold"]} if baseline else {}
    )
    contributions = (
        _compute_contributions(baseline["summary"], ablations)
        if baseline and ablations else {}
    )
    impact = (
        _compute_impact_matrix(baseline["per_fold"], ablations)
        if baseline and ablations else {}
    )

    cfg = cache["config_snapshot"]
    lines: list[str] = []
    lines.append("# Dataset Selection Report")
    lines.append("")
    lines.append(f"Subject: `{config.TRAINING_SUBJECT}`  ")
    lines.append(f"Pool root: `{TRAINING_DATA_ROOT}`  ")
    lines.append(f"Sessions in pool: {len(sessions)}  ")
    lines.append(f"Generator: `evaluate_training_candidates.py`")
    lines.append("")

    # ---------------- Pipeline ----------------
    lines.append("## Pipeline")
    lines.append("")
    lines.append(f"- Mu band {cfg['LOWCUT']:.0f}-{cfg['HIGHCUT']:.0f} Hz, "
                 f"window {cfg['CLASSIFY_WINDOW']} ms, motor channel subset "
                 f"({len(cfg['MOTOR_CHANNEL_NAMES'])} channels)")
    lines.append(f"- Beta-band covariances additionally extracted for multi-band "
                 f"Fisher screening and for the production tangent-space feature stack")
    lines.append(f"- Per-session shrinkage (λ={cfg['SHRINKAGE_PARAM_XGB']:.3f}) + "
                 f"Riemannian whitening via "
                 f"`Generate_Riemannian_adaptive.compute_processed_covariances"
                 f"(model_type='xgb')`; each session's covariances are centered on "
                 f"the identity, so tangent representations are directly comparable "
                 f"across sessions")
    lines.append(f"- Tangent-space reference fitted on the train split only, per fold "
                 f"(leakage-free)")
    lines.append(f"- Feature vector = concatenated mu-band and beta-band tangent "
                 f"representations (matches production XGB decoder)")
    lines.append(f"- XGBoost: max_depth={cfg['XGB_MAX_DEPTH']}, "
                 f"n_estimators={cfg['XGB_N_ESTIMATORS']}, "
                 f"learning_rate={cfg['XGB_LEARNING_RATE']}")
    lines.append(f"- CV: session-LOO (GroupKFold, one fold per session). "
                 f"Subject-wise LOSO is not used because sessions from the same "
                 f"subject are recorded weeks apart with variable equipment, so "
                 f"session is the appropriate grouping unit for generalizability here.")
    lines.append("")

    # ---------------- Fisher ----------------
    if fisher_info:
        lines.append("## Riemannian Fisher screening")
        lines.append("")
        lines.append("### Method")
        lines.append("")
        lines.append("For each session independently, MI and REST whitened covariances "
                     "are summarised by their Riemannian (Fréchet) means. The squared "
                     "Riemannian Fisher score is the affine-invariant analogue of the "
                     "classical Fisher criterion (between-class / within-class variance):")
        lines.append("")
        lines.append("`fisher = d_R(μ_MI, μ_REST)^2  /  mean( ⟨d_R(C, μ_MI)^2⟩_MI, "
                     "⟨d_R(C, μ_REST)^2⟩_REST )`")
        lines.append("")
        lines.append("It is computed independently in the mu and beta bands; the "
                     "per-session screening value is `max(fisher_mu, fisher_beta)`, "
                     "so a session passes if *either* band is discriminative. Sessions "
                     "below the mean−std threshold are dropped before LOO.")
        lines.append("")
        lines.append("### Results")
        lines.append("")
        lines.append(f"- Across {len(sessions)} sessions: "
                     f"mean(max-fisher)={fisher_info['mean']:.3f}, "
                     f"std={fisher_info['std']:.3f}")
        lines.append(f"- Screening threshold (mean − std) = "
                     f"**{fisher_info['threshold']:.3f}**")
        n_kept = sum(1 for s in sessions if s.get("fisher_screened_in"))
        lines.append(f"- Kept: {n_kept} / Dropped: {len(sessions) - n_kept}")
        lines.append("")

    # ---------------- Direction alignment ----------------
    if direction:
        lines.append("## Direction alignment")
        lines.append("")
        lines.append("### Method")
        lines.append("")
        lines.append("For each session we compute its MI-vs-REST discriminant direction "
                     "in the tangent space at the identity (natural base point because "
                     "per-session whitening centers covariances at I), concatenated "
                     "across mu and beta bands. The alignment score of session *s* is "
                     "the mean cosine similarity between *s*'s discriminant and every "
                     "other session's discriminant:")
        lines.append("")
        lines.append("`alignment(s) = mean_{t ≠ s} cos(v_s, v_t)`")
        lines.append("")
        lines.append("Interpretation:")
        lines.append("")
        lines.append("- `≈ +0.3 … +1.0` — majority-aligned (typical MI direction)")
        lines.append("- `≈ 0` — orthogonal / novel mode (keep — different MI, not wrong MI)")
        lines.append("- `< −0.2` — anti-aligned: this session's MI direction coincides "
                     "with the pool's REST direction. Fisher can still be high, so this "
                     "flag catches sessions that *look* discriminative but contradict the "
                     "rest of the pool.")
        lines.append("")

    # ---------------- LOO ----------------
    if loo_is_new:
        bs = baseline["summary"]
        ns = null_baseline["summary"]
        n_screened = len(baseline["per_fold"])

        lines.append("## LOO cross-validation")
        lines.append("")
        lines.append("### Method")
        lines.append("")
        lines.append(f"Session-LOO on the {n_screened} Fisher-screened sessions "
                     f"(GroupKFold, one fold per session). For each fold: tangent "
                     f"references fit on the training covariances only, features "
                     f"projected, StandardScaler + XGBoost. Four metrics are reported "
                     f"per fold:")
        lines.append("")
        lines.append("- **Acc** — argmax accuracy at threshold 0.5")
        lines.append("- **AUC** — ROC AUC (threshold-independent ranking quality). "
                     "Most relevant for a decoder whose behavior depends on a "
                     "probability threshold that may be retuned later.")
        lines.append("- **LogLoss** — probability calibration quality (lower is better)")
        lines.append("- **BalAcc** — balanced accuracy (robust to per-session MI/REST "
                     "count imbalance)")
        lines.append("")
        lines.append("Fold-level spread (std, min, max) is reported alongside the mean "
                     "because session-to-session stability matters for generalizability: "
                     "a model with high mean and high variance fails badly on some "
                     "sessions and is not a safe basis for selection.")
        lines.append("")
        lines.append("### Baseline (full Fisher-screened pool)")
        lines.append("")
        lines.append("| Metric | Mean | Std | Min | Max |")
        lines.append("|---|---:|---:|---:|---:|")
        for m in METRIC_NAMES:
            s = bs[m]
            lines.append(f"| {_METRIC_LABEL[m]} | "
                         f"{_fmt(s['mean'])} | {_fmt(s['std'])} | "
                         f"{_fmt(s['min'])} | {_fmt(s['max'])} |")
        lines.append("")

        lines.append("### Null baseline (labels shuffled within each session)")
        lines.append("")
        lines.append("Labels are permuted *within each session* (preserving per-session "
                     "class balance), then the same LOO CV is run. This anchors the "
                     "chance floor for this exact pipeline on this pool. Baseline "
                     "metrics meaningfully above null are the generalizable signal; "
                     "any stage producing values near null should be discounted.")
        lines.append("")
        lines.append("| Metric | Baseline | Null | Gap (baseline − null) |")
        lines.append("|---|---:|---:|---:|")
        for m in METRIC_NAMES:
            b_mean = bs[m]["mean"]
            n_mean = ns[m]["mean"]
            gap = (b_mean - n_mean) if (np.isfinite(b_mean) and np.isfinite(n_mean)) else float("nan")
            lines.append(f"| {_METRIC_LABEL[m]} | "
                         f"{_fmt(b_mean)} | {_fmt(n_mean)} | {_fmt(gap, '+.4f')} |")
        lines.append("")

        lines.append("### Per-session contribution")
        lines.append("")
        lines.append("`contribution(i, metric) = baseline(metric) − LOO(pool \\ {i}, metric)`  "
                     "(sign flipped for log-loss so positive always means *i* helps).")
        lines.append("")
        lines.append("Positive = including *i* improves the pool's ability to classify "
                     "the *other* sessions. This is the inclusion criterion. A session's "
                     "own held-out accuracy is informative but not decisive — a session "
                     "that is easy to predict but contributes nothing to predicting "
                     "others is not useful for generalization.")
        lines.append("")
        lines.append("See the per-session table below for each session's contribution "
                     "across all four metrics.")
        lines.append("")

        # ------------- Per-session-pair impact matrix -------------
        # Summary: for each session i, mean/min impact on others for AUC (primary metric).
        # Then list the top-K most-negative pairs across all metrics that agree.
        lines.append("### Per-session-pair impact")
        lines.append("")
        lines.append("`impact(i → j, metric) = baseline_fold(j, metric) − "
                     "LOO(pool \\ {i})_fold(j, metric)` (sign-flipped for log-loss). "
                     "Positive = including *i* helps predict *j*; negative = including "
                     "*i* hurts the pool's prediction of *j*. A session with positive "
                     "mean contribution but large negative impacts on specific others "
                     "is not generalizable — it is shifting the mean while trading "
                     "accuracy between sessions.")
        lines.append("")
        lines.append("#### Impact summary per session (AUC)")
        lines.append("")
        lines.append("| Subject | Session | Mean impact on others | Min impact | Max impact | # others hurt (<0) |")
        lines.append("|---|---|---:|---:|---:|---:|")

        def _impact_row_sort(s):
            i_fp = s["file_path"]
            row = impact.get(i_fp, {})
            vals = [row[j]["auc"] for j in row if np.isfinite(row[j].get("auc", np.nan))]
            mean_v = float(np.mean(vals)) if vals else -1e9
            return (-mean_v, s["subject_id"], s["session_tag"])

        screened_sessions = [s for s in sessions if s.get("fisher_screened_in")]
        for s in sorted(screened_sessions, key=_impact_row_sort):
            i_fp = s["file_path"]
            row = impact.get(i_fp, {})
            vals = np.array([row[j]["auc"] for j in row], dtype=float)
            vals = vals[np.isfinite(vals)]
            if len(vals) == 0:
                continue
            mean_v = float(vals.mean())
            min_v  = float(vals.min())
            max_v  = float(vals.max())
            n_hurt = int((vals < 0).sum())
            lines.append(f"| {s['subject_id']} | {s['session_tag']} | "
                         f"{_fmt(mean_v, '+.4f')} | {_fmt(min_v, '+.4f')} | "
                         f"{_fmt(max_v, '+.4f')} | {n_hurt} |")
        lines.append("")

        # Top negative pairs (i hurts j) — AUC, top 10.
        neg_pairs = []
        for i_fp, row in impact.items():
            for j_fp, metrics in row.items():
                v = metrics.get("auc", float("nan"))
                if np.isfinite(v) and v < 0:
                    neg_pairs.append((v, i_fp, j_fp))
        neg_pairs.sort(key=lambda t: t[0])  # most negative first
        if neg_pairs:
            fp_to_s = {s["file_path"]: s for s in sessions}
            lines.append("#### Most-negative pairs (AUC) — top 10")
            lines.append("")
            lines.append("| *i* (included) | *j* (predicted) | Impact (AUC) |")
            lines.append("|---|---|---:|")
            for v, i_fp, j_fp in neg_pairs[:10]:
                si = fp_to_s[i_fp]; sj = fp_to_s[j_fp]
                lines.append(f"| {si['subject_id']} {si['session_tag']} | "
                             f"{sj['subject_id']} {sj['session_tag']} | "
                             f"{_fmt(v, '+.4f')} |")
            lines.append("")

    # ---------------- Cross-reference: alignment × contribution ----------------
    if loo_is_new and direction:
        lines.append("## Cross-reference: alignment × contribution")
        lines.append("")
        lines.append("Flags combine direction alignment (Does this session's MI direction "
                     "agree with the pool?) with LOO contribution (Does including it help "
                     "classify the others?). The concerning case is **alignment < 0 but "
                     "contribution > 0**: the session is anti-aligned yet appears to help, "
                     "which usually means it's raising mean accuracy through a mechanism "
                     "that doesn't generalize (e.g. easy REST trials).")
        lines.append("")
        lines.append("| Subject | Session | Alignment | Contrib Acc | Contrib AUC | Flag |")
        lines.append("|---|---|---:|---:|---:|:---|")
        flagged_rows = []
        for s in sessions:
            if not s.get("fisher_screened_in"):
                continue
            fp = s["file_path"]
            align = s.get("alignment_score", float("nan"))
            c_acc = contributions.get(fp, {}).get("acc", float("nan"))
            c_auc = contributions.get(fp, {}).get("auc", float("nan"))
            flags = []
            if np.isfinite(align) and align < -0.2:
                flags.append("anti-aligned")
            if np.isfinite(c_auc) and c_auc < 0:
                flags.append("hurts pool (AUC)")
            if np.isfinite(align) and np.isfinite(c_acc) and align < 0 and c_acc > 0:
                flags.append("suspicious helper")
            flag_str = ", ".join(flags) if flags else "—"
            if flags:
                flagged_rows.append((s, align, c_acc, c_auc, flag_str))
        flagged_rows.sort(key=lambda r: (r[1], -r[3]))  # most anti-aligned first
        for s, align, c_acc, c_auc, flag_str in flagged_rows:
            lines.append(f"| {s['subject_id']} | {s['session_tag']} | "
                         f"{_fmt(align, '+.3f')} | {_fmt(c_acc, '+.4f')} | "
                         f"{_fmt(c_auc, '+.4f')} | {flag_str} |")
        if not flagged_rows:
            lines.append("| — | — | — | — | — | no sessions flagged |")
        lines.append("")

    # ---------------- Per-session table ----------------
    lines.append("## Per-session table")
    lines.append("")
    lines.append("| Subject | Session | Category | Fisher (max) | Alignment | "
                 "Screened | HO Acc | HO AUC | Contrib Acc | Contrib AUC | Unique |")
    lines.append("|---|---|---|---:|---:|:---:|---:|---:|---:|---:|:---:|")

    def _row_sort(s):
        fp = s["file_path"]
        c_auc = contributions.get(fp, {}).get("auc", -1e9)
        if not np.isfinite(c_auc):
            c_auc = -1e9
        return (-c_auc, s["subject_id"], s["session_tag"])

    for s in sorted(sessions, key=_row_sort):
        fp = s["file_path"]
        fisher = s.get("fisher_score_max")
        align  = s.get("alignment_score")
        bl_fold = baseline_per_fold_by_fp.get(fp, {})
        acc     = bl_fold.get("acc")
        auc     = bl_fold.get("auc")
        c_acc   = contributions.get(fp, {}).get("acc")
        c_auc_v = contributions.get(fp, {}).get("auc")
        cat = s["visual_category"]
        if s.get("aliased_categories"):
            cat += f" (+{','.join(s['aliased_categories'])})"
        lines.append(
            f"| {s['subject_id']} | {s['session_tag']} | {cat} | "
            f"{_fmt(fisher, '.3f')} | {_fmt(align, '+.3f')} | "
            f"{'yes' if s.get('fisher_screened_in') else 'no'} | "
            f"{_fmt(acc, '.3f')} | {_fmt(auc, '.3f')} | "
            f"{_fmt(c_acc, '+.4f')} | {_fmt(c_auc_v, '+.4f')} | "
            f"{'yes' if s['subject_id'] in unique_subjs else 'no'} |"
        )
    lines.append("")

    if loo and not loo_is_new:
        lines.append("> **Note:** the cached LOO results use an older schema. "
                     "Re-run `--stage loo` to populate the multi-metric, null-baseline, "
                     "and pair-impact sections above.")
        lines.append("")

    os.makedirs(os.path.dirname(report_path), exist_ok=True)
    with open(report_path, "w") as f:
        f.write("\n".join(lines))
    print(f"[report] wrote {report_path}")


# ---------------- CLI ----------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--stage",
        required=True,
        choices=["cache", "fisher", "direction", "loo", "report", "all"],
        help="which pipeline stage to run",
    )
    parser.add_argument("--cache-path",  default=DEFAULT_CACHE_PATH)
    parser.add_argument("--report-path", default=DEFAULT_REPORT_PATH)
    args = parser.parse_args()

    if args.stage in ("cache",     "all"): stage_cache(args.cache_path)
    if args.stage in ("fisher",    "all"): stage_fisher(args.cache_path)
    if args.stage in ("direction", "all"): stage_direction(args.cache_path)
    if args.stage in ("loo",       "all"): stage_loo(args.cache_path)
    if args.stage in ("report",    "all"): stage_report(args.cache_path, args.report_path)


if __name__ == "__main__":
    main()
