from rehamove import *          # Import our library
import time
import math 

r = Rehamove("/dev/ttyUSB0")    # Open USB port (on Windows)
r.change_mode(0)                # Change to low-level mode (each pulse is sent separtely)

MTS_intensity = 5	# in mA for motor-threshold stimulation
MTS_duration = 30 	# in ms 

STS_intensity = 5		# in mA for sensory threshold stimulation
STS_duration = [3,6,11] 	# in seconds for distal, both , proximal

t_init = time.time()
t_passed = time.time()

r.change_mode(1)                                      # Change to mid-level mode (pulse frequency is generated by the device
r.set_pulse(STS_intensity, 1)                                   # Set the pulse used in mid-level mode
r.run("blue", 0.1, STS_duration[0]*1000)                             # Run that set pulse every 100 ms for 10s total
time.sleep(1)

# r.run("red", 0.1, STS_duration[1]*1000)                             # Run that set pulse every 100 ms for 10s total
# r.run("blue", 0.1, STS_duration[1]*1000)                             # Run that set pulse every 100 ms for 10s total
# time.sleep(2)

# r.run("red", 0.1, STS_duration[2]*1000)                             # Run that set pulse every 100 ms for 10s total
# time.sleep(1)

# r.pulse("blue", MTS_intensity, MTS_duration*1000)     # Send pulse every second
# r.pulse("red", MTS_intensity, MTS_duration*1000)     # Send pulse every second

# r.change_mode(0)                                      # Change to mid-level mode (pulse frequency is generated by the device

# while t_passed - t_init < STS_duration[0]:
# 	# r.pulse("blue", 6, 600) # Send pulse every second
# 	r.pulse("red", 5, 500) # Send pulse every second
# 	time.sleep(1/30)
# 	t_passed = time.time()


# while t_passed - t_init < STS_duration[1]:
# 	r.pulse("blue", 5, 500) # Send pulse every second
# 	r.pulse("red", 5, 500) # Send pulse every second
# 	time.sleep(1/30)
# 	t_passed = time.time()

# while t_passed - t_init< STS_duration[2]:
# 	r.pulse("blue", 5, 500) # Send pulse every second
# 	r.pulse("red", 5, 500) # Send pulse every second
# 	time.sleep(1/30)
# 	t_passed = time.time()


# r.pulse("blue", MTS_intensity, MTS_duration*1000)     # Send pulse every second
# r.pulse("red", MTS_intensity, MTS_duration*1000)     # Send pulse every second


# for i in range(0, 5):

# r = Rehamove("/dev/ttyUSB0")                          # Open USB port (on Linux)
# r.version()                                           # Query battery life
# r.battery()                                           # Query battery life
# r.pulse("blue", 5, 200)                               # Send single pulse (currentIntensity, pulseWidth in micro seconds)
# r.custom_pulse("blue", [(5.0, 200), (-5.0, 200)])     # Send pulse with custom waveform
# r.change_mode(1)                                      # Change to mid-level mode (pulse frequency is generated by the device
# r.set_pulse(5, 200)                                   # Set the pulse used in mid-level mode
# r.run("blue", 100, 10000)                             # Run that set pulse every 100 ms for 10s total
# exit()      